---
title: "How to set up Lockdown Browser"
output: 
  html_document: 
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This course requires the use of LockDown Browser for taking exams to ensure fair testing environment for everyone. This is a customized web browser that prevents users from accessing other applications or going to other websites during an exam. You cannot take exams requiring LockDown Browser on any other Internet browser (Internet Explorer, Firefox, Safari, etc.) and that you cannot exit the LockDown Browser until the quiz is submitted.

<p><iframe src="https://www.youtube.com/embed/XuX8WoeAycs" width="560" height="314" allowfullscreen="allowfullscreen"></iframe></p>

### You need to download and install LockDown Browser from this [link](https://www.respondus.com/lockdown/download.php?id=451214388){target="_blank"}. 
Note: Do not download a copy of LockDown Browser from elsewhere on the Internet; those versions won't work at our institution.

### Update required

- Once you have the LockDown Browser installed, launch the browser.
- Click on "i" icon at the top
- Click on the button that says "Check for newer version"
- Install the update

### Review this list prior to taking your quiz or exam:

- Wired internet connection is highly recommended. If your wireless connection drops at all, you will get disconnected from the Canvas server and may have to have it reset by your instructor.
- Ensure you are in a location where you won't be interrupted
- Turn off all mobile devices, phones, etc.
- Clear your desk of all external materials — books, papers, other computers, or devices
- No one else should be in the room with you
- Remain at your desk or workstation for the duration of the test
- Launch the LockDown Browser and choose Canvas from the drop-down menu
- Log in using your WSU access ID and password; navigate to your course
- Go to your Exam Content area and select the exam
- The remaining steps of the Startup Sequence will depend on settings chosen by your instructor.
- Follow the instructions and note your progress along the top of the screen.
- If you encounter a problem, select the It’s not working link for troubleshooting tips.
- The test will begin after the Startup Sequence is complete.
- If an interruption occurs during the exam, briefly explain what happened by speaking directly to your webcam
- You cannot exit the exam until all questions are completed and submitted for grading.
