---
title: "Lecture 9 - Data definition and manipulation language (DDL&DML)"
author:
output: 
  html_document:
    theme: cosmo
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fontawesome)
library(tidyverse)
library(kableExtra)
```

# `r fa("youtube", fill = "steelblue")` Video

<iframe width="800" height="450" src="https://www.youtube.com/embed/oO1glVuU14k" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>
<iframe width="800" height="450" src="https://www.youtube.com/embed/4nxLvYidlVk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>
<iframe width="800" height="450" src="https://www.youtube.com/embed/dHrNCZCGq1o" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>
<iframe width="800" height="450" src="https://www.youtube.com/embed/JvmnhCgEWU4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>

# `r fa("folder-open", fill = "steelblue")` Slide
``` {r echo=FALSE}
df_slide <- tribble(
  ~text, ~chapter,
  "5-1", "[Data Definition Language (DDL)](s5-1_DDL.pdf){target=\"_blank\"}",
  "5-2", "[Data Manipulation Language (DML)](s5-2_DML.pdf){target=\"_blank\"}",
  "5-3", "[Constraints](s5-3_constraint.pdf){target=\"_blank\"}",
  "5-4", "[Transaction control](s5-4_TC.pdf){target=\"_blank\"}",
)

knitr::kable(df_slide, escape = F, col.names=NULL) %>%
  kable_styling(bootstrap_options = "striped")
```

# `r fa("book", fill = "steelblue")` Reading
``` {r echo=FALSE}
df_reading <- tribble(
  ~text, ~chapter,
  "HVT", "Ch 6. Introduction to SQL",
  "JC", "Ch 3. Table creation and management",
  "JC", "Ch 4. Constraints",
  "JC", "Ch 5. Data manipulation and transaction control",
)

knitr::kable(df_reading, escape = F, col.names=NULL) %>%
  kable_styling(bootstrap_options = "striped")
```

