---
title: "Lecture 2 - Entity-Relatioship Diagram 1"
author:
output: 
  html_document:
    theme: cosmo
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fontawesome)
library(tidyverse)
library(kableExtra)
```

# `r fa("youtube", fill = "steelblue")` Video

<iframe width="800" height="450" src="https://www.youtube.com/embed/WmInR4PajW4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>
<iframe width="800" height="450" src="https://www.youtube.com/embed/lGTSAwIhcYo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>
<iframe width="800" height="450" src="https://www.youtube.com/embed/INc5ZxThlq8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>
<iframe width="800" height="450" src="https://www.youtube.com/embed/x1rfvWEO11o" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>

# `r fa("folder-open", fill = "steelblue")` Slide
``` {r echo=FALSE}
df_slide <- tribble(
  ~text, ~chapter,
  "2-1", "[Entity](s2-1_entity.pdf){target=\"_blank\"}",
  "2-2", "[Attribute](s2-2_attribute.pdf){target=\"_blank\"}",
  "2-3", "[Relationship](s2-3_rel1.pdf){target=\"_blank\"}",
  "2-4", "[Cardinality](s2-4_rel2.pdf){target=\"_blank\"}",
)

knitr::kable(df_slide, escape = F, col.names=NULL) %>%
  kable_styling(bootstrap_options = "striped")
```

# `r fa("book", fill = "steelblue")` Reading
``` {r echo=FALSE}
df_reading <- tribble(
  ~text, ~chapter,
  "HVT", "Ch 2. Modeling data in the organization",
)

knitr::kable(df_reading, escape = F, col.names=NULL) %>%
  kable_styling(bootstrap_options = "striped")
```

