---
title: "Lecture 13 - Subquery"
author:
output: 
  html_document:
    theme: cosmo
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(fontawesome)
library(tidyverse)
library(kableExtra)
```

# `r fa("youtube", fill = "steelblue")` Video

<iframe width="800" height="450" src="https://www.youtube.com/embed/DjQfCL658Hs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>
<iframe width="800" height="450" src="https://www.youtube.com/embed/cGUebdfBK2c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>
<iframe width="800" height="450" src="https://www.youtube.com/embed/M-KHEcOSX2A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>
<iframe width="800" height="450" src="https://www.youtube.com/embed/BtJrgArcB2c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data-external="1"></iframe>  
<br>

# `r fa("folder-open", fill = "steelblue")` Slide
``` {r echo=FALSE}
df_slide <- tribble(
  ~text, ~chapter,
  "6-9", "[Subquery 1](s6-9_subq1.pdf){target=\"_blank\"}",
  "6-10", "[Subquery 2](s6-10_subq2.pdf){target=\"_blank\"}",
  "6-11", "[Subquery 3](s6-11_subq3.pdf){target=\"_blank\"}",
  "6-12", "[View](s6-12_view.pdf){target=\"_blank\"}",
)

knitr::kable(df_slide, escape = F, col.names=NULL) %>%
  kable_styling(bootstrap_options = "striped")
```

# `r fa("book", fill = "steelblue")` Reading
``` {r echo=FALSE}
df_reading <- tribble(
  ~text, ~chapter,
  "HVT", "Ch 7. Advanced SQL",
  "JC", "Ch 12. Subqueries and MERGE statements",
  "JC", "Ch 13. Views",
)

knitr::kable(df_reading, escape = F, col.names=NULL) %>%
  kable_styling(bootstrap_options = "striped")
```

